[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ipcriminal-python-xeroxxhah"  # Use a unique name on PyPI
version = "0.1.0"
authors = [
  { name="Muhammad Nauman Azeem", email="xeroxxhah@pm.me" },
]
description = "A Python client for the CriminalIP API. It provides a simple interface for querying IP, domain, and security intelligence data from CriminalIP using your API key."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/XeroxXhah/criminalip-python"
